### ISSUE TITLE
Code-sign the app

### ISSUE THREAD

**Issue by RyKilleen** [RyKilleen/brancato#31]
https://tauri.studio/docs/distribution/sign-windows#bonus-sign-your-application-with-github-actions

**Comment by RyKilleen** [comment]
@SeanKilleen At some point when your free, I'd appreciate your help on getting a hold of the KilleenCode cert. If it's already added on our github org somehow I'm happy to just transfer this repo if that makes life easier. It's not any sort of priority

**Comment by SeanKilleen** [comment]
@RyKilleen it expired because we didn't renew it because of the cost.

However, I think I have a way forward on that. I'll check it tonight and get back to you.

**Comment by RyKilleen** [comment]
No worries, I think you can do it through let's encrypt now

**Comment by SeanKilleen** [comment]
LetsEncrypt actually can't support code signing, because part of that chain of trust is verifying the user's identity (typically done using address, license, FEIN, etc.) -- I had to go through it with the other cert.

However, I have a discount offer from a cert company that may let me get this setup. Missed it yesterday but will try to look today.

**Comment by RyKilleen** [comment]
Closed in #48

**Comment by RyKilleen** [comment]
Re-opening for testing first 😅

**Comment by RyKilleen** [comment]
It's alive!
